### ISSUE TITLE
How-to guide for schematrons

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/TS-EAS-subteam-notes#1]
Just creating a stub issue in our notes section to record that we've been requested to provide an introduction to schematron now that EAD3 recommends using schematron for some of its validation steps.

See [https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/schemas-subteam/meeting-minutes-2017/minutes-2017-01-10.md](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/schemas-subteam/meeting-minutes-2017/minutes-2017-01-10.md)

**Comment by karinbredenberg** [comment]
Draft sent to @kerstarno

**Comment by fordmadox** [comment]
Thanks, @karinbredenberg !  I'm going to close this issue out since we already have this https://github.com/SAA-SDT/EAD3/issues/467.  We can discuss more on today's call.
